name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64]
        include:
          - os: ubuntu-latest
            arch: aarch64
          - os: macos-latest
            arch: arm64
    steps:
      - uses: actions/checkout@v2

      #- name: add submodule
      #  run: |
      #    git submodule add https://github.com/lericson/pylibmc
      #    git submodule init
      #    git submodule update
      #- name: add git repo
      #  run: git clone https://github.com/lericson/pylibmc && cd pylibmc

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up QEMU
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: docker/setup-qemu-action@v1

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel
      - name: Build wheels
        env:
          CIBW_SKIP: "*-musllinux* pp*"
          CIBW_ARCHS: ${{matrix.arch}}
          CIBW_BEFORE_BUILD_LINUX: "yum install -y libmemcached-devel"
          CIBW_BEFORE_BUILD_MACOS: "brew install libmemcached"
        run: |
          cibuildwheel --output-dir wheelhouse
      
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      - name: Build sdist
        run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz      

  upload_pypi:
     needs: [build_wheels, build_sdist]
     runs-on: ubuntu-latest
     #if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
     steps:
       - uses: actions/download-artifact@v2
         with:
           name: artifact
           path: dist

       - uses: actions/download-artifact@v2
         with:
           name: artifact
           path: wheelhouse

       - name: Publish sdist to PyPI
         uses: pypa/gh-action-pypi-publish@master
         with:
           user: ${{ secrets.PYPI_USERNAME }}
           password: ${{ secrets.PYPI_PASSWORD }}

       - name: Publish wheels to PyPI
         uses: pypa/gh-action-pypi-publish@master
         with:
           user: ${{ secrets.PYPI_USERNAME }}
           password: ${{ secrets.PYPI_PASSWORD }}
           packages_dir: wheelhouse/
